### ISSUE TITLE
Error while importing master data

### ISSUE THREAD

**Issue by laborg** [phoenixctms/master-data#1]
```
root@phoenix-test:/ctsms/build/ctsms# sudo -u ctsms /ctsms/dbtool.sh -icp /ctsms/master_data/criterion_property_definitions.csv
```
errors in: 
```
CTSMS_PROPERTIES: /ctsms/properties
2019-04-10 10:14:35: starting...
Phoenix Clinical Trial Management System
version: 1.6.2
instance: phoenix-test/localhost
jvm: 1.8.0_181
task: import criterion properties tables
....
massMail.probandListStatus.id: 2 operator(s)
massMail.fromAddress: 8 operator(s)
massMail.fromName: 8 operator(s)
2019-04-10 17:14:56: ERROR OCCURED
java.lang.IllegalArgumentException: line 288: error reading line
	at org.phoenixctms.ctsms.executable.csv.CsvImporter.readLines(CsvImporter.java:235)
	at org.phoenixctms.ctsms.executable.csv.CsvImporter.loadCriterionProperties(CsvImporter.java:140)
	at org.phoenixctms.ctsms.executable.DBTool.main(DBTool.java:194)
Caused by: java.lang.IllegalArgumentException: unknown selection set service method getLocales
	at org.phoenixctms.ctsms.executable.csv.CriterionPropertyLineProcessor.processLine(CriterionPropertyLineProcessor.java:189)
	at org.phoenixctms.ctsms.executable.csv.LineProcessor.processLine(LineProcessor.java:107)
	at org.phoenixctms.ctsms.executable.csv.CsvImporter.readLines(CsvImporter.java:231)
	... 2 more
```

Related to the time field changes?

**Comment by rkrenn** [comment]
fixed, see https://github.com/phoenixctms/ctsms/commit/ae07d64bb4a08c8283a41d08cb397bbb60451617
